---
title: "Introduction to Analysis of Political Data"
subtitle: <center>P SC 5923-100; CRN 37720</center>
author: "Dr. Samuel Workman"
date: '`r Sys.Date()`'
output: 
  html_document:
    css: my_style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
library(kableExtra)
library(fontawesome)
```

------------------------------------------------------------------------
<div class = "row">
      
<div class = "col-md-6">
<br>`r fa("envelope", fill = "#34A853")` [samuel.workman@ou.edu](mailto:samuel.workman@ou.edu)
<br>`r fa("globe-americas", fill = "blue")` [samuelworkman.org](https://www.samuelworkman.org)
<br>`r fa("twitter", fill = "#1DA1F2")`
[SamuelGWorkman](https://twitter.com/SamuelGWorkman)
<br>`r fa("medium", fill = "black")` [samuelworkman](https://medium.com/@samuelworkman)
</div>
      
<div class = "col-md-6">
<br>**Office Hours:** Remote & By Appointment
<br>**Class Sessions:** Tuesday & Thursday, 1:30--4:20pm
<br>**Office:** Five Partner's Place, Suite 2300
<br>**Classroom:** Burton Hall 0201
</div>
</div>

------------------------------------------------------------------------

## Prerequisites

Graduate standing.

## Course Description

This is an introductory course in data science for political scientists. As such, the course covers the collection and organization of data, issues associated with measurement, describing data quantitatively, and communicating features of data using statistical tables and graphics. We will discuss hypothesis-testing, statistical control, and descriptive inference, how to deal with categorical data, and how to measure association between two variables. The course provides the foundational knowledge needed to learn the the most common statistical estimator in the social sciences - least squares regression.

There are no specific prerequisites for this course, although familiarity with matrix algebra, probability, and working with exponents and logs is helpful. All needed math and coding will be demonstrated and covered in class. Students will implement the techniques from the course using freely available statistical programs. Students should also be ready to work with their own data.

## Learning Objectives

1. Understand the best principles for collecting and organizing data to facilitate analysis and communication.

2. Understand how to evaluate measures of concepts constructed from data.

3. Understand how to design research to facilitate comparison and deal with categorical information.

4. Employ simple hypothesis-testing for descriptive inference.

5. Analyze relationships between two variables.

6. Present and communicate statistical descriptions and analyses in tables and figures.

# Course Administration {.tabset .tabset-fade .tabset-pills}

## Course Texts

Additional texts will be assigned by the instructor and loaned on a weekly basis to students. Each week, students will volunteer to read specific chapters from these texts and give a presentation to the rest of the class the following week. These presentations will be simple and address lessons learned from these texts.

* Karl W. Broman & Kara H. Woo. 2018. [Data Organization in Spreadsheets.](https://doi.org/10.1080/00031305.2017.1375989) *The American Statistician* 72(1): 2--10. DOI: 10.1080/00031305.2017.1375989

* Shannon E. Ellis & Jeffrey T. Leek. 2018. [How to Share Data for Collaboration.](https://doi.org/10.1080/00031305.2017.1375987)
*The American Statistician* 72(1):53--57. DOI: 10.1080/00031305.2017.1375987

* Andrew Gelman. 2011. [Why Tables Are Really Much Better Than Graphs.](https://doi.org/10.1198/jcgs.2011.09166) *Journal of Computational and Graphical Statistics* 20(1): 3--7. DOI: 10.1198/jcgs.2011.09166

* Andrew Gelman, Cristian Pasarica, and Rahul Dodhia 2002. [Let's Practice What We Preach.](https://doi.org/10.1198/000313002317572790) *The American Statistician* 56(2):121--130. DOI: 10.1198/000313002317572790

* Jonathan P. Kastellec and Eduardo L. Leoni. 2007. [Using Graphs Instead of Tables in Political Science.](https://doi.org/10.1017/S1537592707072209) *Perspectives on Politics* 5(4): 755--771. DOI: 10.1017/S1537592707072209

* Amelia McNamara and Nicholas J. Horton. 2018. [Wrangling Categorical Data in R.](https://doi.org/10.1080/00031305.2017.1356375) *The American Statistician* 72(1): 97--104. DOI: 10.1080/00031305.2017.1356375

* Hadley Wickam. 2014. [Tidy Data.](https://www.jstatsoft.org/article/view/v059i10) *Journal of Statistical Software* 59(10): August 2014.

* Samuel Workman. 2020. [Four Principles of Data Collection](https://towardsdatascience.com/four-principles-of-data-collection-82ad07938ac1). *Towards Data Science* May 12, 2020.

## Assessment

The course requirements are geared towards developing students' skills in the entire range of research, analysis, and storytelling with data. The assignments promote the development of the conduct and presentation of research results, including intuitive data visualization. In addition to these, the assignments develop students' ability to synthesize and integrate theories, ideas, and existing research pertaining to these. One or more vignettes will address the practical implementation of these approaches to data using `r fa("r-project", fill = "steelblue")`.

**Participation**. Each Thursday of the course, one or more students will present lessons or takeaways from the week's reading to the rest of the seminar participants. In addition to presentations, each student is expected to participate in class discussion, ask thoughtful questions, and engage the Professor and their peers.

The seminar employs the Peter J. May stellar system of grading for participation. Consistent, engaging, and stellar contributions each week will net the student four stars and the full 20 points for the participation grade. Consistent contributions that are solid will net three stars and 14 points. Acceptable contributions will net two stars and 10 points. Sporadic contributions will be awarded one star and net 4 points. Occasional contributions will net one star and 2 points. An unwillingness to participate, whether because of lack of preparedness or shyness, will be awarded zero stars, and zero participation points. You are either an academic or training to work in a public organization. Its not time to be shy.

**Conceptualization and Measurement Paper**. Students will write a paper that explores the conceptualization and measurement of a concept of interest to them. This paper will rely on at least 6 independent sources and can include scholarly studies, government or think-tank reports, or interest group policy briefs. In 2-3 pages single-spaced, students will evaluate the conceptualization of the key concept and its measurement, including strengths and weaknesses and alternative measurement approaches. 

**Descriptive Vignette**. Each student will use descriptive statistics and graphics to describe one or more variables in a data set of their choosing. Once completed, the results and the code will be including in a vignette along with the student's detailed explanation of the code. Each student or team will then be graded by at least one of their peers, along with a grade assigned by the Professor.

## Important Due Dates

| Assignment    | Due Date    | Percentage of Grade |
| :------------- |:----------:| -----:|
| Participation | Each Meeting | 20 |
| Concept Paper | September 16th | 40 |
| Descriptive Vignette | October 14th | 40 |

## Course Policies

### Statistical Computing

In this course, we will utilize `r fa("r-project", fill = "steelblue")` for all statistical procedures and protocols. Specific assignments call for the developing your own code and being able to explain to a knowledgeable audience.

### Late & Makeup Policy

All  assignments  are  due  on  time.  Since  all  assignments  are  specified  well  in  advance, or alternatively are completed contemporaneously, late assignments will not be accepted and will receive a grade of zero. Exceptions for late work will be granted for only the most dire of circumstances.

### Professional Communications

Most general course administration questions can be answered by referring to the syllabus. I tend to respond to student email only once every 24 hours. Depending on when I check my email on a given day, the earliest time at which a response may be expected is within 24 hours. Please be aware that I also do not respond to emails on weekends or holidays.

## University Policies

### Religious Observances

The University's policy with regard to religious observances is as follows: "It is the policy of the University to excuse the absences of students that result from religious observances and to provide without penalty for the rescheduling of examinations and additional required class work that may fall on religious holidays."

Students should notify the Professor of a pending absence by the second meeting of the class. Since religious observances are specified well in advance of the academic calendar, students should communicate this well in advance of important dates for the course.

### Academic Dishonesty

Students who violate University rules on scholastic dishonesty are subject to disciplinary penalties and action, including the possibility of failure in the  course and/or dismissal from the University. Since such dishonesty harms the individual, all students, and the integrity of the University, policies on scholastic dishonesty will be strictly enforced and penalties pursued to the maximum extent of the policy.

### Reasonable Accomodations Policy

*Students must initiate their request for reasonable accommodations through the Disability Resource Center (DRC).* Students requiring academic accommodation should contact the Accessibility and Disability Resource Center for assistance at (405) 325-3852 or TDD: (405) 325-4173. For more information please visit [DRC's website](http://www.ou.edu/drc/home.html). Any student in this course who has a disability that may prevent him or her from fully demonstrating his or her abilities should contact me personally as soon as possible so we can discuss accommodations necessary to ensure full participation and facilitate your educational opportunities.

### Title IX Resources and Reporting Requirement

For any concerns regarding gender-based discrimination, sexual harassment, sexual assault, dating/domestic violence, or stalking, the University offers a variety of resources. To learn more or to report an incident, please contact the Sexual Misconduct Office at (405) 325-2215 (8 to 5, M-F) or smo@ou.edu. Incidents can also be reported confidentially to OU Advocates at (405) 615-0013 (phones are answered 24 hours a day, 7 days a week).  Also, please be advised that a professor/GA/TA is required to report instances of sexual harassment, sexual assault, or discrimination to the Sexual Misconduct Office. Inquiries regarding non-discrimination policies can be directed to University Equal Opportunity Officer and Title IX Coordinator at (405) 325-3546 or smo@ou.edu . For more information, visit the [Institutional Equity Office](http://www.ou.edu/eoo.html).

### Adjustments for Pregnancy/Childbirth-Related Issues

Should you need modifications or adjustments to your course requirements because of documented pregnancy-related or childbirth-related issues, please contact your professor or the Disability Resource Center at (405) 325-3852 as soon as possible. Also, see [answers](http://www.ou.edu/eoo/faqs/pregnancy-faqs.html) to commonly asked questions.

### Mental Health Support Services

If you are experiencing any mental health issues that are impacting your academic performance, counseling is available at the University Counseling Center (UCC). The Center is located on the second floor of the Goddard Health Center, at 620 Elm Rm. 201, Norman, OK 73019. To schedule an appointment call (405) 325-2911. For more information please visit the webpage [here](http://www.ou.edu/ucc).


## Course Schedule

### Week 1: Research as Comparison & the Role of Data

* Browman & Woo (2018)

### Week 2: Statistics in the Process of Research

* Wickam (2014)

### Week 3: Conceptualization and Measurement

* Workman (2020)

### Week 4: Descriptive Inference

* Ellis & Leek (2018)

### Week 5: Analysis of Variance & Categorical Data

* McNamara & Horton (2018)

### Week 6: Covariance & Correlation

* Gelman, Pasarica, & Dodhia (2002)

### Week 7: Visualizing Data

* Kastellec & Leoni (2007)

### Week 8: Constructing Tables

* Gelman (2011)


